### ISSUE TITLE
Interface re-arranging

### ISSUE THREAD

**Issue by AmyOlex** [VCUWrightCenter/TopExApp#106]
Per our meeting today we decided to alter the following with the TopEx GUI:

- Change the "Cluster" tab title to "Parameters"
- Move the uploading of stopwords to the Parameters tab at the bottom.
- Move the Run button to be next to the Information and Acknowledgements buttons.  Color it green and probably should make the font and button a little bigger so it stands out.
- Change the name of the "File Manager" tab to "Load Data".
- Re-arrange the Load Data tab to the following 2 sections in this order:
1. Clustering Corpus (Required)
2. Expansion Corpus (Optional)

- Under the Clustering Corpus section include the following instructions paragraph:  Choose the set of texts you want to analyze with TopEx.  You must **_choose only one_** of the 4 options below.  If you choose to run a PubMed search from within TopEx then your query will be run after pressing the Run button.
- Under the Clustering Corpus section have the following subsections:
1. From Text Files <button name: Choose directory containing files...>
2. From CSV File <button name: Choose CSV file...>
3. From MEDLINE Formatted File <button name: Choose MEDLINE file...>
4. From PubMed Search

- The first 3 subsections should just have a button associated with them.  The 4th section should have the 2 fields that are currently present.  Please change the default 50 to 100 as it returns better results.

**Comment by etfrenchvcu** [comment]
@burdettep We'll need to pass the input type to the cluster POST

**Comment by burdettep** [comment]
This has been done. @AmyOlex I ended up going a different route with the location of the "Run Cluster" button. Please let me know if it is acceptable to you. I didn't place it next to the Information and Acknowledgements buttons because I didn't want it to be visible an page load to users. It could be confusing there because there is nothing data-wise that is associated with it.

**Comment by AmyOlex** [comment]
Thanks Peter!  I'm not super happy with it where it is, but we can leave it and get feedback from users. A few requests...

1. Please change the "CLUSTER!" button wording to "Run TopEx!".  
2. In the Expansion Corpus paragraph, can you change "Background Corpus" to "Expansion Corpus".
3. On the Parameters Tab, can you move the Custom Stopwords loading section to be right below the checkbox for "Custom stopwords only?" and change the font to a secondary header so it fits in the "Sentence Embedding" section?

Thanks!!!

**Comment by burdettep** [comment]
No problem! I've made the changes.

-Peter Burdette

Web Developer
Wright Center for Clinical and Translational Research
Virginia Commonwealth University
Office Phone: 804-827-1544
Cell Phone: 804-397-0951

**Comment by burdettep** [comment]
All updates have been made.
