### ISSUE TITLE
Update export options

### ISSUE THREAD

**Issue by etfrenchvcu** [VCUWrightCenter/TopExApp#41]
@AmyOlex @burdettep What's the point of the "Export graph data". The resulting json file doesn't seem very useful to anyone as currently formatted. Can we replace that button with the export that is currently in the Import/Export tab? I think it would make sense to feature this "export for later" option more prominent.

**Comment by AmyOlex** [comment]
I would like to add in the exporting of raw data for the word cloud for Phase 2.

**Comment by etfrenchvcu** [comment]
@AmyOlex Added exporting word cloud data. Please test.
