### ISSUE TITLE
Removing Negative Space

### ISSUE THREAD

**Issue by AmyOlex** [VCUWrightCenter/TopExApp#46]
Need to re-arrange tabs to reduce negative space and make plot bigger.

**Comment by burdettep** [comment]
Added drawer functionality for the panels.  Greatly increased graph/main area real estate. @AmyOlex

**Comment by AmyOlex** [comment]
This is working nicely, but I have 2 issues:

1) the dots are now overlapping the axis and being drawn off the plotting area (see screen shot).
2) When TopEx first starts it might not be clear to click on the hamburger menu.  Would it be possible to add a welcome screen with brief instructions that disappears when the plot is generated?

![image](https://user-images.githubusercontent.com/7603758/99724251-5a5b1b00-2a81-11eb-9a1a-624dc83152a7.png)

**Comment by burdettep** [comment]
@AmyOlex this has been addressed.
