### ISSUE TITLE
Add estimated time to completion

### ISSUE THREAD

**Issue by AmyOlex** [VCUWrightCenter/TopExApp#49]
Look into adding an estimated time to completion, or a warning if corpus is large.

**Comment by AmyOlex** [comment]
maybe we don't need the time, but an update of which step it is on wrt to the new manuscript that is coming out ("Normalizing", "Sentence Representation", "Clustering"?

**Comment by etfrenchvcu** [comment]
@AmyOlex I have this functionally working, but I'll need a list of the exact wording you would like to use for each of the steps.

@burdettep This is currently just being printing in a text string above the buttons to run clustering and reclustering. It could probably use some beautification.

**Comment by burdettep** [comment]
@AmyOlex and @etfrenchvcu this has been completed. Take a look and let me know if you approve of the design (I can change it).  I decided to go with a full screen overlay status view once the user clusters/reclusters so no unintentional clicks can take place.

**Comment by etfrenchvcu** [comment]
@burdettep I'm happy with the loading screen. One minor change I would request is that when the clustering completes, the sidebar menu auto-collapses to show the main panel. Currently, when clustering completes, the scatterplot is still greyed out until the user manually clicks to collapse the side menu. Looks good. Thanks!

**Comment by burdettep** [comment]
@etfrenchvcu I have implemented this new functionality.  I decided to collapse the sidebar at runtime instead of when the clustering completes because it's a cleaner look.  Thanks for the suggestion!
