### ISSUE TITLE
Graphs need axis names

### ISSUE THREAD

**Issue by AmyOlex** [VCUWrightCenter/TopExApp#50]
Add axis names to graph based on visualization method (e.g. UMAP_1, UMAP_2 or TSNE_1, TSNE_2, etc).

**Comment by burdettep** [comment]
@AmyOlex this has been addressed.

**Comment by AmyOlex** [comment]
This works fine, except when you recluster, then they change to "undefined_1" and "undefined_2".  Is there a way to fix that?

**Comment by burdettep** [comment]
@AmyOlex this has been addressed.
