### ISSUE TITLE
addition to acknowledgements

### ISSUE THREAD

**Issue by AmyOlex** [VCUWrightCenter/TopExApp#61]
Can you add the following to the Acknowledgements after the first paragraph?

"In addition, Evan French and Peter Burdette from VCU's Wright Center for Clinical and Translational Research Informatics Core have been working tirelessly with Amy Olex to get TopEx ready for public release.  Thanks to both of you for your amazing work!"

**Comment by burdettep** [comment]
@AmyOlex nice! I went to go make the update and saw you had already done it.
