### ISSUE TITLE
K-means only uses Euclidean

### ISSUE THREAD

**Issue by AmyOlex** [VCUWrightCenter/TopExApp#84]
Need to add some type of error message or notification that the K-Means clustering algorithm only uses Euclidean distance.  If Kmeans is chosen the code automatically uses Euclidean distance regardless of what is chosen on the interface.  Just need to add something to notify users of this.

**Comment by burdettep** [comment]
@AmyOlex I have added a conditional message for when users select K-Means as the clustering method.
